### ISSUE TITLE
preg_replace: /e modifier is deprecated

### ISSUE THREAD

**Issue by nuxodin** [jjriv/emogrifier#151]
Great Lib!

I get the Deprecated-Warnings:
preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in /web/junior-atelier.ch/m/mail1/lib/Emogrifier.php on line 287

**Comment by oliverklee** [comment]
Hi! Thanks for the bug report. Does this problem also occur with the latest version on master? (There is no preg_replace on line 287 of the current version.)

**Comment by nuxodin** [comment]
Ups sorry, my mistake, everything is perfect
