### ISSUE TITLE
Document how we handle XHTML

### ISSUE THREAD

**Issue by oliverklee** [jjriv/emogrifier#153]
… and add some unit tests for this behavior.

**Comment by Renkas** [comment]
```php
return mb_convert_encoding($xmlDocument->saveHTML(), self::ENCODING, 'HTML-ENTITIES');
```
This row is messing up my HTML. It double encodes the entities I already have in my (XHTML) document. If I return $xmlDocument->saveHTML() directly then everything seems to be fine. All entities that were not encoded in input are already encoded by DOMDocument

**Comment by oliverklee** [comment]
@Renkas Thanks for the bug report. Could you please open a ticket for this (and, even better, a PR)? Thanks!

**Comment by oliverklee** [comment]
(or comment in #172)
