### ISSUE TITLE
Add ability to disable inlining CSS from <style> tags

### ISSUE THREAD

**Issue by erikhansen** [jjriv/emogrifier#155]
I am getting ready to use Emogrifier on a project where we do *not* want to have Emogrifier look for CSS styles inside of `<style>` blocks. I recommend that this option be added to the Emogrifier class so that users can disable the parsing of `<style>` tags.

This feature is mentioned in the third bullet point here: https://github.com/jjriv/emogrifier#caveats

I plan on submitting a pull request that implements this feature. 

I plan on creating the following methods:

* `setOptions` - This will accept an associative array of options and will store that array on a private `$options` property. 
e.g., `array('parse_inline_style_tags' => false, )`
* `getOption` - This method will accept an option key and will return the value if found, null if not
* I'll modify the `getCssFromAllStyleNodes` method to return if `getOption('parse_inline_style_tags')` == true.

@oliverklee - Can you confirm that you'll be able to merge this PR into master? e.g., do you consider it a good idea? I read through the entire conversation surrounding the [open PR](https://github.com/jjriv/emogrifier/pull/106) and realize that my approach for implementing options is slightly different than @timothyasp's approach of storing the options on an explicitly defined parameter. If you prefer one approach over the other, let me know.

**Comment by oliverklee** [comment]
I like adding that option.

However, I'm not in favor of just passing in an options array as this will make catching typos in the array keys very hard. Instead, I'd prefer to have a two fields $isInlineStylesParsingEnabled and $isStyleBlocksParsingEnabled (both having true as the default value), and two dedicated methods to disabled these two options (disableInlineStylesParsing() and disableStyleBlocksParsing()).

I'll then be happy to review a pull request for this (including the necessary unit tests to cover the new behavior).

**Comment by erikhansen** [comment]
@oliverklee After I wrote up my proposed approach, I thought about the issue with misspelled options. Your approach makes perfect sense. I will work on a pull request to add the new functionality + unit tests.

Splitting "style blocks" and "inline styles" makes a lot of sense.

**Comment by oliverklee** [comment]
Great, thanks!
