### ISSUE TITLE
No support for !important?

### ISSUE THREAD

**Issue by SimonEast** [jjriv/emogrifier#160]
It seems that `!important` isn't honoured correctly.

When given this input...

```html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<style>
		.test {color: red;}
		div {color: green !important;}
	</style>
</head>
<body>
	<div class="test">hello</div>
</body>
</html>
```

The result (incorrectly) is...

```html
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body>
	<div class="test" style="color: red;">hello</div>
</body>
</html>
```

**Comment by hybridwebdev** [comment]
Actually you're wrong, it is assigned correctly. Your definition of div applies to all generic div elements, however the class definition overwrites it.

**Comment by SimonEast** [comment]
No, I don't believe that's correct.

If you run this fiddle in your browser you'll see that the text appears green, not red.

http://jsfiddle.net/simoneast/h5c1s5c1/

**Comment by oliverklee** [comment]
!important currently indeed is not supported. Would you be willing to tackle this in a pull request?

**Comment by SimonEast** [comment]
I'd be happy to give it a go, but work is hectic at the moment and I may not have time for a few weeks.  Perhaps this missing feature could be mentioned in the README until support is provided?

**Comment by oliverklee** [comment]
Thanks for mentioning it. I've added the documentation in PR #161.

Looking forward to your pull request, @SimonEast! <3
