### ISSUE TITLE
Investigate whether we can get rid of any re-encoding altogether

### ISSUE THREAD

**Issue by oliverklee** [jjriv/emogrifier#172]
i.e., whether we can drop the ENCODING constant.

**Comment by Renkas** [comment]
I'll add the same info here also:

```php
return mb_convert_encoding($xmlDocument->saveHTML(), self::ENCODING, 'HTML-ENTITIES');
```
This row is messing up my HTML. It double encodes the entities I already have in my (XHTML) document. If I return $xmlDocument->saveHTML() directly then everything seems to be fine. All entities that were not encoded in input are already encoded by DOMDocument.

Right now in my case the code is not working as expected.
