### ISSUE TITLE
Document emogrifyBodyContent in the README

### ISSUE THREAD

**Issue by oliverklee** [jjriv/emogrifier#212]
Hi @vanderlee, could you please add a few lines of documentation for emogrifyBodyContent to the README so that others know they can use it? Thanks!

If you put "[ci skip]" (without the quotes) into the commit message description, you can skip the (in this case unnecessary) Travis build.

**Comment by vanderlee** [comment]
I'm done.

This, including all the tweaks, could have been done many hours of work ago and I no longer feel my time is best spent continuing on.

Feel free to take over this and my other changes.

**Comment by oliverklee** [comment]
This is the documentation for #206.
