### ISSUE TITLE
Document the required PHP version

### ISSUE THREAD

**Issue by rroblik** [jjriv/emogrifier#226]
Hi,

I've read nothing about PHP minimum version needed to be able to use Emogrifier.
I updated to last version, and my scripts stop working.

I think that it is because "new" (php 5.4+) array syntax :
`private $excludedSelectors = [];`

As i'm runing php 5.3.3 I need (and maybe other people) need to downgrade ...

Thanks to document.

**Comment by oliverklee** [comment]
Thanks for the suggestion. Currently, it's only enforced (and kind of documented) in the composer.json. I'll take care of documenting it in the README.
