### ISSUE TITLE
Negative attribute selectors a[href^="tel"]

### ISSUE THREAD

**Issue by digitaloutback** [jjriv/emogrifier#227]
Is this a known issue?

**Comment by oliverklee** [comment]
No, not as far as I know.

@digitaloutback Could you please provide steps to reproduce the problem, the expected result and the actual result?

And would you be willing to provide a pull request that has a unit test for the problem and a fix? That would be awesome!

**Comment by MattiJarvinen-BA** [comment]
Symfony css-selector would handle this but maybe just implementing these rules in Emogrifier would help a lot.

https://github.com/symfony/css-selector/blob/master/XPath/Extension/AttributeMatchingExtension.php#L34 and https://github.com/symfony/css-selector/blob/master/XPath/Extension/AttributeMatchingExtension.php#L110

Also adding support for adding xPathRules would be nice.
