### ISSUE TITLE
data uris not supported

### ISSUE THREAD

**Issue by sanderkruger** [jjriv/emogrifier#235]
Style declarations with images referenced as a [Data URI](https://en.wikipedia.org/wiki/Data_URI_scheme) will break.

The regex in the method parseCssDeclarationBlock probably trips over the semicolon in the data URI syntax and mistakes it for a style declaration delimiter.

I'm not enough of a crack in regular expressions to correct this.

**Comment by sanderkruger** [comment]
I found that the problem is not so much with the regular expression as with the code that splits a css block into declarations. It uses explode(';' for this, chopping up the data uri.

I tried out a workaround that works (but isn't bullet-proof) for the most common data uris:
first replace ';base64' with '@base64', then do all the parsing then reverse the replacement.

If this is good enough for all the users of this project, I can make a PR for it.

**Comment by oliverklee** [comment]
Sounds good!

**Comment by oliverklee** [comment]
Fixed in #238 / #243.
