### ISSUE TITLE
Noisy error on malformed CSS

### ISSUE THREAD

**Issue by Synchro** [jjriv/emogrifier#237]
Much like #179, I've been getting this from something malformed:
```
2015-09-30 14:43:49 DOMXPath::query(): Invalid predicate
#0 System_ErrorHandler->ERROR_HANDLER
#1 DOMXPath->query line 287
#2 Pelago\Emogrifier->process line 211
#3 Pelago\Emogrifier->emogrify line 44
```

That line is:

    $nodesMatchingCssSelectors = $xpath->query($this->translateCssToXpath($selector['selector']));

So it may well be fixed by a fix for #179 by eliminating the bogus selector, but it shouldn't throw a noisy error like this anyway. Better to just ignore the content. When I've tracked down the content responsible for this error, I'll add it in here so we can build a test for it.

**Comment by oliverklee** [comment]
What CSS is causing this problem?

**Comment by Renkas** [comment]
I got the same problem.

 in /var/www/vendor/pelago/emogrifier/Classes/Emogrifier.php – DOMXPath::query('//a[href^="tel"]') at line 723

**Comment by oliverklee** [comment]
Okay, so it looks like Emogrifier currently does not support negative attribute selectors (i.e., this is missing feature). Anyone willing to implement this?

**Comment by Synchro** [comment]
That just sounds like XPath and CSS selectors do not share the same syntax for that kind of lookup. I suspect in my case it was simply malformed CSS rather than a missing feature - e.g. if someone puts HTML tags in the CSS, which I've seen. From the source of my CSS, I strongly suspect it's just random junk rather than anything as sophisticated as this missing selector, so the rename may not be quite appropriate.

**Comment by oliverklee** [comment]
Okay, I've reverted the changes to this ticket. Thanks for the input! (We already have #227 for the missing feature anyway.)

**Comment by oliverklee** [comment]
@Renkas: So it looks like you're experiencing #227.

**Comment by Synchro** [comment]
I've managed to track down some CSS that's causing this error - it's an empty media query.

In the Emogrifier class, the `extractMediaQueriesFromCss` method finds the media queries, but having an empty one makes it go out of sync and it starts treating a selector as properties.

I've set up the content and the regex it uses [here](https://regex101.com/r/fQ8kA9/1), and you can see it going wrong.

Following on from that, when it gets to `existsMatchForCssSelector`, the first CSS selector it passes is:

```
}

table.body
```

Which is invalid, but still gets translated into the invalid XPath:

```xpath
//}//table[contains(concat(" ",@class," "),concat(" ","body"," "))]
```

After which I get the error:

```
2016-04-27 14:43:19 DOMXPath::query(): Invalid expression
#0 My_ErrorHandler->ERROR_HANDLER
#1 DOMXPath->query line 956
#2 Pelago\Emogrifier->existsMatchForCssSelector line 913
#3 Pelago\Emogrifier->copyCssWithMediaToStyleNode line 391
#4 Pelago\Emogrifier->process line 276
#5 Pelago\Emogrifier->emogrify line 44
```

So it would be good if Emogrifier could cope with a missing media query body.

Meanwhile, I'll try to track down why my media queries are empty - I supect an old version of CSSTidy may be at fault.
