### ISSUE TITLE
Placeholders for variables with curly brackets are HTML encoded by emogrification

### ISSUE THREAD

**Issue by nathanpitman** [jjriv/emogrifier#240]
I'm using the Emogrifier to emogrify a template which includes placeholders for dynamic content in the format:

    {my_var}

This is all good with the exception of when a var appears as a href value, i.e.

    <a href="{my_var}">

After emogrification this is returned as:

    <a href="%7Bmy_var%7D">

Any thoughts on how I might prevent that? :)

**Comment by oliverklee** [comment]
Which version are you using? e29867470e5baa9d03e1f717fc9bd0202400fc55 should have fixed this.

**Comment by nathanpitman** [comment]
I think I worked it out, curly brackets in URLs are not valid, therefore they are encoded when the document tree is parsed. I've just implemented the following after Emogrification in my controller...

    $replace = array('%7B' => '{', '%7D' => '}');
    $body = str_replace(array_keys($replace), array_values($replace), $body);

Thanks for the quick reply though. Great library! :)

**Comment by oliverklee** [comment]
:+1:
