### ISSUE TITLE
Previous changes to parseCssDeclarationBlock()

### ISSUE THREAD

**Issue by bramley** [jjriv/emogrifier#251]
I'm looking at the regular expression in method parseCssDeclarationBlock(), as discussed in issue  "Fix parsing of CSS for data-uri's #238", but then came across this other open issue on the same function  "refactor of parseCssDeclarationBlock" #92.

This looks confusing to me, as the approach proposed in #92, to use explode() instead of the regex, is what used to happen until an earlier change [CLEANUP] Rename and clean up the cssStyleDefinitionToArray method https://github.com/jjriv/emogrifier/commit/49d0735a3b4b322c2782a86588fe7078cafc4978

Do you remember the reason for that change, as I agree that splitting into property/value is simpler than the regex approach? Is the intention to allow only validly formatted properties? I don't know enough about the package to know whether that is necessary but the current approach doesn't quite work in a couple of respects.

**Comment by oliverklee** [comment]
If I remember correctly, the point of 49d0735 was to simplify the code and make it more readable.

#92 was just an idea to make the code even more simple and faster. If the proposed breaks the functionality, we shouldn't go that way.

As far as accepting only valid CSS goes, we indeed should only accept valid CSS (as invalid CSS rules are to be ignored as per the specs, which also is how the browsers do it).

**Comment by oliverklee** [comment]
If the proposed changes break anything, this would be a sign that we should first add some unit tests for the cases that would break.

**Comment by bramley** [comment]
I might not have been clear. The aim of #92 is to change the code to roughly what it was before 49d0735.
But I will ignore #92 then, and have added some test cases that currently fail, which shouldn't.

**Comment by oliverklee** [comment]
:+1:

**Comment by oliverklee** [comment]
Great! Closing this ticket and looking forward to your PR with the added test cases.
