### ISSUE TITLE
3 tests fail on line-endings on Windows

### ISSUE THREAD

**Issue by sanderkruger** [jjriv/emogrifier#253]
The following tests fail on my Windows system:
emogrifyReturnsCompleteHtmlDocument
emogrifyBodyContentReturnsBodyContentFromHtml
emogrifyBodyContentReturnsBodyContentFromContent

All three give the following warning:
 #Warning: Strings contain different line endings!

I'd suggest normalizing line endings before comparing output in the test cases.

**Comment by oliverklee** [comment]
Either that, or (even better) we use always the correct line ending for those tests: From the error message, it looks like PHP uses Unix line endings (chr(10)) even on Windows for rendering the HTML. So we should always use chr(10) in those tests, and maybe re-add the class constant self::LF in the test case for that.

**Comment by oliverklee** [comment]
Hi @sanderkruger, could you please test whether the changes in PR #263 fix the tests for you, and then report back in that PR? Thanks!
