### ISSUE TITLE
first-child and last-child selectors are broken

### ISSUE THREAD

**Issue by bramley** [jjriv/emogrifier#286]
There was a basic misunderstanding of what the selector first-child means in the fix for issue  https://github.com/jjriv/emogrifier/pull/257

From https://developer.mozilla.org/en-US/docs/Web/CSS/%3Afirst-child
The :first-child CSS pseudo-class represents any element that is the first child element of its parent.

The code, and the unit tests, think that it means the first child of the named element.

        // :first-child
        '/([^\\/]+):first-child/i'                 => '\\1/*[1]',

            'BODY:first-child matches first child'
                => ['body:first-child {' . $styleRule . '} ', '#<p class="p-1" style="' . $styleRule . '">#'],

Similarly for last-child, and possibly other similar selectors.

**Comment by oliverklee** [comment]
@bramley: Could you please test the PR for this (#293) and also verify it by reading?

I've used the XPath equivalents as listed on https://en.wikibooks.org/wiki/XPath/CSS_Equivalents .
