### ISSUE TITLE
Actual requirements

### ISSUE THREAD

**Issue by demis-palma** [jjriv/emogrifier#294]
The requirements in the readme file state that the PHP extension Multibyte String is required:
*"PHP from 5.4 to 7.0 (with the mbstring extension)"*
while looking at the code, all the mb_* function calls have been removed a lot of time ago.
Does the documentation needs to be updated, or the dependency from mbstring extension still exist?

**Comment by oliverklee** [comment]
Hi @demis-palma, thanks for noticing this! Indeed, we can remove this requirement from the documentation and the composer.json. Would you be willing to provide a pull request for this (including a changelog entry)?

**Comment by demis-palma** [comment]
I'm not a composer expert, but I'll try it with pleasure. Thanks for the opportunity.

**Comment by demis-palma** [comment]
[Just done](https://github.com/jjriv/emogrifier/pull/295), please check.
