### ISSUE TITLE
Emogify breaks Url parameters in <a> tags

### ISSUE THREAD

**Issue by CodeAndWeb** [jjriv/emogrifier#300]
`<a href="https://www.example.com/test?a=1&b=2">test</a>`

becomes

`<a href="https://www.example.com/test?a=1&amp;b=2">test</a>`

& must not be escaped into &amp; in the URL

**Comment by oliverklee** [comment]
Yes, it must be escaped as a HTML entity for the document to be valid HTML as the ampersand is one the the reserved characters. The URL in the browser when clicking the link will have the ampersand entity decoded.
