### ISSUE TITLE
Add support for wildcards in attribute selectors

### ISSUE THREAD

**Issue by ernsto** [jjriv/emogrifier#303]
Hello, 

currently it is not possible to use a wildcard selector like `[class*=foobar]`. 

**Example (wrong xpath result):**
```
CSS: .search-container [class*=foobar]
Xpath: //*[contains(concat(" ",@class," "),concat(" ","search-container"," "))]//[class*=foobar]
```

Therefore i added another element to the `$xPathRules` array which will convert the css selector into a correct xpath expression: 

```
'/\\[(\\w+)\\*=([\\w-]+)\\]/'               => '*[contains(concat(" ",@\\1," "),"\\2")]',
```

**Example (correct xpath result):**
```
CSS: .search-container [class*=foobar]
Xpath: //*[contains(concat(" ",@class," "),concat(" ","search-container"," "))]//*[contains(concat(" ",@class," "),"foobar")]
```

I will make a pull request for this feature.

**Comment by oliverklee** [comment]
This has been implemented in #330.
