### ISSUE TITLE
Add ability to load complete HTML document and return inlined version

### ISSUE THREAD

**Issue by clarinetlord** [jjriv/emogrifier#305]
One limiting factor of using this library is that if the HTML and CSS are one complete document, like a stored template, the client has to manually break up the HTML document in order to provide Emogrifier with the HTML within the <body> and and the CSS within the <style> tag. After the inlining, the client has to then reassemble the modified document before passing along to a mailer or other consumer of the full HTML document. It would be great if the Emogrifier class itself, or maybe a separate wrapper service class could provide this common need.

**Comment by oliverklee** [comment]
Emogrifier also processes style nodes in the HTML HEAD. Is this what you need?

**Comment by clarinetlord** [comment]
Apologies because I recently came across this library and maybe I don't understand the functionality well enough yet, but the documentation makes it seem like you need to provide the HTML and CSS separately. Are you saying If I just do 

`$Emogrifier = new Emogrifier($complete_html_document);`
`$html = $Emogrifier->emogrify();`

does that give me back the complete inlined HTML document?

**Comment by oliverklee** [comment]
Yes, exactly:
https://github.com/jjriv/emogrifier/blob/master/Tests/Unit/EmogrifierTest.php#L1252

If you think that we should make this more clear in the documentation, would you be willing to provide a pull request for this?

**Comment by clarinetlord** [comment]
Sure, I'd be happy to do that. Might not be for a few days, but I'll get to it soon.
