### ISSUE TITLE
HTML entities break when ISO encoded

### ISSUE THREAD

**Issue by sjdaws** [jjriv/emogrifier#312]
Hi,

I have some HTML which contains non-breaking spaces, if it is put through the emogrifier it returns with a UTF-8 character which is incorrectly encoded.

Example HTML:
```html
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
</head>
<body>
&nbsp;Hello
</body>
</html>
```

Expected output:
```html
<!DOCTYPE html>
<html>
<head><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"></head>
<body>
&nbsp;Hello
</body>
</html>
```

Actual output:
```html
<!DOCTYPE html>
<html>
<head><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"></head>
<body>
�Hello
</body>
</html>
```

The problem goes away if I remove the charset header but I'm unsure whether there is another approach. This also happens with other entities such as &Ograve;.

Any ideas on why this is happening?

Thanks,
Scott.

**Comment by oliverklee** [comment]
Emogrifier does not support ISO8859-1 - it only supports UTF-8 (as stated in the Caveats section in the README).

Does the problem still occur if you switch to UTF-8?

**Comment by sjdaws** [comment]
I missed that part of the read me, if the meta tag is removed or its set to UTF-8 it works correctly

Sorry about thst
