### ISSUE TITLE
Not encode some symbols

### ISSUE THREAD

**Issue by CrazyClicker** [jjriv/emogrifier#313]
Hey there! 
Thx for the great plugin, I have a question - it is possible NOT to convert symbols such as "[" or "%" to "%5B%" etc inside tag attributes? Some sort of options or...

`<a href="[% link %]">`

**Comment by oliverklee** [comment]
Hi @CrazyClicker: Actually, I don't know. At least it's currently not configurable. If you would be willing to come up with a pull request to change the default behavior (including the unit tests for it), this would be very welcome. :-)
