### ISSUE TITLE
Image CSS "height: auto" doesn't work

### ISSUE THREAD

**Issue by blindner** [jjriv/emogrifier#351]
Hi there, I found a glitch where I'm not sure if the issue is on my side or on emogrifier:

I have an image to test, where I expect to be updated, which works fine. However the 
definition of height: auto ends in an empty height tag.

My code is as follows:

http://pastebin.com/zpgNYMgN

The result of the created <img> tag is as follows:
![empty_height](https://cloud.githubusercontent.com/assets/6814656/19376450/1d8800dc-9208-11e6-804b-7e8e1c0ac042.png)

The height is an empty tag and causes a error in my logs:
DOMXPath::query(): Invalid expression in [emogrifier/Classes/Emogrifier.php, line 366]

Any idea?
Thanks a lot!

**Comment by oliverklee** [comment]
Hi @blindner, thanks for the bug report and the steps to reproduce! I'll have a look at it during the next days. (And if you would like to give it a shot yourself, more power to you.)

**Comment by oliverklee** [comment]
Oh, and this most probably is a bug in Emogrifier, not in your HTML/CSS.

**Comment by blindner** [comment]
Hi Oliver, yes I think so... at least I couldn't fix it on my end ;-)

I suggest to remove the width in case of "auto" as the width only allows pixels in this usage as per: http://www.w3schools.com/tags/att_img_width.asp

**Comment by dereuromark** [comment]
Looks like the same thing as https://github.com/jjriv/emogrifier/issues/350 .
