### ISSUE TITLE
How to get more information about wrong xPath selector

### ISSUE THREAD

**Issue by OzzyCzech** [jjriv/emogrifier#360]
We are using emogrifier a lot but sometimes is hard to get right information what's wrong. Mostly we get just `PHP Warning: DOMXPath::query(): Invalid expression in /vendor/pelago/emogrifier/Classes/Emogrifier.php:366`

there is my proposal how to get more information about that type of warnings:

```
class Emogrifier extends \Pelago\Emogrifier {

  protected function process(\DOMDocument $xmlDocument) {

    set_error_handler(
      function ($errno, $errstr, $errfile, $errline, $errcontext) {
        if (isset($errcontext['cssRule']['selector'])) {
          throw new \Exception(
              $errstr . ' in selector >> ' . $errcontext['cssRule']['selector'] . ' <<'
          );
        }
      }, E_WARNING
    );

    parent::process($xmlDocument);

    restore_error_handler();
  }

}
```

It's throw an error like : `DOMXPath::query(): Invalid expression in selector >> html input[disabled] << ` now you can easily found what's wrong.

**Comment by oliverklee** [comment]
Hi @OzzyCzech, great proposal! Would you be willing to create a pull request for this (including unit tests)?

**Comment by OzzyCzech** [comment]
sure

**Comment by OzzyCzech** [comment]
done, check latest version
