### ISSUE TITLE
Release 1.2.0

### ISSUE THREAD

**Issue by oliverklee** [jjriv/emogrifier#372]
@jjriv I'd like to release version 1.2.0 soon so we can get the bug fixes and features that already have been merged out of the door. I'll then move the remaining open tickets/PRs from 1.2.0 to 1.3.0.

Would that be okay with you?

**Comment by jjriv** [comment]
Go for it. I trust your judgement more than my own :)

____________________________________________________________________

John Reeve
jreeve@pelagodesign.com<mailto:jreeve@pelagodesign.com>
Intervals | Web-based Time, Task & Project Management | www.myintervals.com<http://www.myintervals.com>
____________________________________________________________________
