### ISSUE TITLE
Management of fallback styles

### ISSUE THREAD

**Issue by prioritario71** [jjriv/emogrifier#376]
Hi all.
Is there any way to inline these styles:
```
.myclass {
width: 98%;               /* fallback for browsers without support for calc() */
width: calc(100% - 1em);
}
```
Actually, Emogrifier uses only one of the two properties (the last width value).
Thank you a lot
-Francesco

**Comment by oliverklee** [comment]
Hi Francesco, no, there is no way to inline this. Sorry.

**Comment by prioritario71** [comment]
Hi Oliver. Thank you for your answer.
However, I changed Associative Array containing the original styles in a simple Array with numeric indexes ( and array($attributeName,$attributeValue) as values) and obtained what I needed.
-Francesco

**Comment by oliverklee** [comment]
Hi @prioritario71, great! Would you be willing to create a pull request for this change (including the unit tests to cover the new behavior including the edge cases)? Then we can integrate this.
