### ISSUE TITLE
Comment Tag'd Styles Fail

### ISSUE THREAD

**Issue by maoxiong** [jjriv/emogrifier#377]
Sorry, I didn't know a better title.

I using tiny_mce for a project which automatically puts the html comment tags around any inline styles found in the body area.

This then causes emogrify to give an error :" Uncaught exception 'InvalidArgumentException' with message 'DOMXPath::query(): Invalid expression in selector >>"

Working HTML:
`<html>
<body>
<style type="text/css"> 
	.header a{font-family:"Comic Sans MS", cursive, sans-serif;} 
</style>

	<table border="0" cellspacing="0" cellpadding="0" style="width: 100%;">
	<tr>
		<td class="header"><a href="#">Forward</a> <a href="#">Unsubscribe</a>
	</tr>
	</table>

</body>
</html>`

After TinyMCE Failing HTML:
`<html>
<body>
<style type="text/css"></style>

	<table border="0" cellspacing="0" cellpadding="0" style="width: 100%;">
	<tr>
		<td class="header"><a href="#">Forward</a> <a href="#">Unsubscribe</a>
	</tr>
	</table>

</body>
</html>`

For now, I'm just kludging the tiny_mce output, but it would be nice if I didn't have to :)

EDIT: I think the code is getting hidden because of the tags, sample file uploaded.
[demo.txt](https://github.com/jjriv/emogrifier/files/855963/demo.txt)

**Comment by oliverklee** [comment]
Inside CSS, you need to use /* */ as comment marks. HTML comment marks will make the CSS invalid, causing parsing errors.

Did you comment out the code, or did TinyMCE do that?

**Comment by oliverklee** [comment]
Oh, I missed the part where you mentioned that it's TinyMCE that did that. Could you please report there that it needs to use CSS comment markers instead of HTML comment markers? Thanks!

**Comment by maoxiong** [comment]
Unfortunately the project is using an old version of tiny_mce, so it may be fixed in the latest version, just I can't switch to it :(

Ok - so I guess I'll leave my kludging in then! Thanks!
