### ISSUE TITLE
> :first-child, > :last-child, and multiple attributes selectors generate erroneous XPath

### ISSUE THREAD

**Issue by ma-boily** [jjriv/emogrifier#383]
The following selectors seem to generate invalid XPath, crashing the whole parser:

With `:first-child`:
```
  .an-element > :first-child {
    /** Any rules **/
  }
```

With `:last-child`:
```
  .an-element > :last-child {
    /** Any rules **/
  }
```

Multiple attributes:
```
  * input[text*="anytext"][type="text"] {
    /** Any rules **/
  }
```

No regex seem to match any of these 3 cases, causing an `InvalidArgumentException` to be thrown (at https://github.com/jjriv/emogrifier/blob/master/Classes/Emogrifier.php#L1532)

**Comment by oliverklee** [comment]
@ma-boily Thanks for the detailed bug report! Could you please open separate tickets for each issue? (Tickets for multiple issues are really a pain to work with.) Thanks!

**Comment by ma-boily** [comment]
@oliverklee Thanks for the prompt reply. I've split the 3 problems in two separate issues (:first-child and :last-child seem to be going to need a very similar fix). The third one though, seems a lot trickier from my understanding (as it uses regex for matching and replacing, it'd need an alternate way to iterate on all selectors).

Opened issues: #384 and #385

**Comment by oliverklee** [comment]
@ma-boily Thanks! ❤️
