### ISSUE TITLE
Configure a GitHub oauth token

### ISSUE THREAD

**Issue by oliverklee** [jjriv/emogrifier#76]
everzet/capifony#358
https://coderwall.com/p/kz4egw

**Comment by webdevilopers** [comment]
:+1:

**Comment by oliverklee** [comment]
This is what the configuration file looks like at the TYPO3 project:
https://review.typo3.org/#/c/40687/2/.travis.yml

**Comment by jjriv** [comment]
Oliver,

I am sorry for the delay. I was on vacation and just returned today.

If I add the token to the .travis.yml file it should work?

Would it be easier if I emailed you the token directly and have you add it? My github skills are rusty. Or, if you could give me some basic step by step instructions, I can do the update and commit.

Thanks!

John

____________________________________________________________________

John Reeve
jreeve@pelagodesign.com<mailto:jreeve@pelagodesign.com>
Intervals | Web-based Time, Task & Project Management | www.myintervals.com<http://www.myintervals.com>
____________________________________________________________________

**Comment by oliverklee** [comment]
@jjriv I think only you can do this because you are the owner of the Travis account.

This is how to do this:

1. Create a new read-only oAuth token and store it somewhere on your computer.
2. Install RubyGems on your computer
3. gem install travis
4. travis encrypt GITHUB_COMPOSER_AUTH=yourOAuthTokenFromStep1
5. modify our .travis.yml as in https://review.typo3.org/#/c/40687/2/.travis.yml , but use the encrypted value from step 4

This is the Travis documentation on encryption keys: http://docs.travis-ci.com/user/encryption-keys/

**Comment by jjriv** [comment]
Oliver,

I hit a snag trying to install travis. I am using Centos 6.6 but the repos don't go higher than Ruby 1.8.7. I could email you the key and you could encrypt it. Or, if there was another way to run travis encrypt I could do it there.

Here is the error:

[root@a1sb ~]# gem install travis
ERROR:  Error installing travis:
        highline requires Ruby version >= 1.9.3

Here are some links to what's going on:
https://github.com/JEG2/highline/issues/129
https://sourcegraph.com/github.com/JEG2/highline

Any other ideas?

John

**Comment by oliverklee** [comment]
As far as I understand it, it's you who needs to do the encrypting (because it's your Travis account where Emogrifier is located).

You can install Ruby via RVM instead of via your Linux' packages:

    \curl -sSL https://get.rvm.io | bash
    rvm get stable
    rvm install 2.2
    rvm use 2.2 --default

https://rvm.io/rvm/basics
