### ISSUE TITLE
403 errors in Travis during composer install

### ISSUE THREAD

**Issue by oliverklee** [jjriv/emogrifier#90]

**Comment by oliverklee** [comment]
We have this problem again. Sigh.

(Actually, we have this problem when there are more than a few builds per day.)

**Comment by oliverklee** [comment]
https://translate.google.com/translate?sl=auto&tl=en&js=y&prev=_t&hl=de&ie=UTF-8&u=http%3A%2F%2Fblog.champs-libres.coop%2Fdev%2F2015%2F01%2F30%2Fauthenticate-against-github-travis-composer.html&edit-text=&act=url

**Comment by oliverklee** [comment]
It looks like we actually need to create the oauth token (#76).

**Comment by oliverklee** [comment]
I've opened a ticket for Travis CI: https://github.com/travis-ci/travis-ci/issues/4073

**Comment by jjriv** [comment]
Thanks. Let me know if there is anything I can do to help.

____________________________________________________________________

John Reeve
jreeve@pelagodesign.com<mailto:jreeve@pelagodesign.com>
Intervals | Web-based Time, Task & Project Management | www.myintervals.com<http://www.myintervals.com>
____________________________________________________________________

**Comment by oliverklee** [comment]
This should be fixed by #223.
