### ISSUE TITLE
Installing as dependency of a package fails

### ISSUE THREAD

**Issue by oligriffiths** [jjriv/emogrifier#91]
Hi

I'm writing a package that requires the emogrifier as a dependency of the package, I get an error when trying to install my package, saying that there is no matching package for the emogrifier require.

- oligriffiths/emails-component dev-master requires pelago/emogrifier dev-master-> no matching package found.

However if installing as a require in the root composer.json the package installs fine.

Any ideas?

oli

**Comment by oliverklee** [comment]
Closing because there has been no feedback for more than six months. @oligriffiths Please feel free to reopen this issue if the problem still occurs for you.

**Comment by yellowmamba** [comment]
I bumped this issue as well today, and @JANorman was right. I was using `dev-master` of this package, but I didn't update the `minimum-stability` flag, so it was reporting the package was not found. As long as you add `"minimum-stability": "dev"` in the `composer.json` file, it should work.

**Comment by oliverklee** [comment]
@yellowmamba Thanks for the additional information! So all is as it should be, right?

**Comment by yellowmamba** [comment]
@oliverklee Yeah, as far as I can see, there's nothing wrong here. It's just that people can forget to specify the minimum stability (which defaults to `stable`) when they don't use comparable versions of a package.

**Comment by oliverklee** [comment]
@yellowmamba But installing the released versions (e.g., 1.1.0) without changing default minimum stability works fine?

**Comment by yellowmamba** [comment]
@oliverklee I haven't tried that, but I presume it would work fine. Composer takes tags as stable.
