### ISSUE TITLE
refactor of parseCssDeclarationBlock

### ISSUE THREAD

**Issue by jdchmiel** [jjriv/emogrifier#92]
Creating this ticket per request  to not leave comments in the code:

if (!preg_match('/ *([A-Za-z\\-]+) *: *([^;]+) */', $declaration, $matches)) {
                 continue;
}
// can we remove this regex entirely and replace with an explode on :, and conditional on resulting array being 2 strings?

It seems like this regex is only verifying that we have a single css declaration, and then using the regex match for the propertyName and propertyValue.  I added the note because in the back of my head I thought an explode on the colon, and then verifying the resultant array has exactly 2 elements, and then using the 1st as propertyName and second as propertyValue would be quicker than a regex.

**Comment by oliverklee** [comment]
This will probably break the parsing (as mentioned in #251). Closing.
