### ISSUE TITLE
Semantic versioned releases

### ISSUE THREAD

**Issue by markguinn** [jjriv/emogrifier#97]
Would it be possible to use github's release feature and semantic versioning? It would make dependencies much easier/safer in composer.

**Comment by gabrieldamour** [comment]
Can we add the release number somewhere in a file of the project (in README, Emogrifier.php or elsewhere) so it can be parsed and used by a tool using the lilbrary ?

**Comment by oliverklee** [comment]
Hi Gabriel,

thanks for the suggestion (which I :+1:). :-) Do you have a good example of a format which would be best both for parses and humans?

**Comment by gabrieldamour** [comment]
Hi Oliver
I'm not a specialist of that, but I can suggest a few tips:
* attach it to the most important file, the one that will be present in every usage of the lib (ie Emogrifier.php might be a better choice than README.md)
* insert it as a comment at the beginning of the file
* Precede it with a constant string on the same line (for more robust regexp parsing): eg: `Version: 1.0.0`
* stick to the chosen format and location (file and line number) later, obviously to avoid breaking third party lib code.

Here is a few examples I can think of:
* [Flexslider](https://github.com/woothemes/FlexSlider/blob/master/jquery.flexslider.js)
* [Colorbox](https://github.com/jackmoore/colorbox/blob/master/jquery.colorbox-min.js)
* [Sharrre](https://github.com/Julienh/Sharrre/blob/master/jquery.sharrre.min.js)
